export const tableList = [
  { tableNo: "1" },
  { tableNo: "2" },
  { tableNo: "3" },
  { tableNo: "4" },
  { tableNo: "5" },
  { tableNo: "6" },
  { tableNo: "7" },
  { tableNo: "8" },
  { tableNo: "9" },
  { tableNo: "10" },
  { tableNo: "11" },
  { tableNo: "12" },
  { tableNo: "13" },
  { tableNo: "13-1" },
  { tableNo: "14" },
  { tableNo: "14-1" },
  { tableNo: "15" },
  { tableNo: "16" },
  { tableNo: "16-1" },
  { tableNo: "17" },
  { tableNo: "18" },
  { tableNo: "19" },
  { tableNo: "20" },
  { tableNo: "21" },
  { tableNo: "21" },
  { tableNo: "22" },
  { tableNo: "23" },
  { tableNo: "24" },
  { tableNo: "25" },
  { tableNo: "배달-1" },
  { tableNo: "배달-2" },
  { tableNo: "배달-3" },
];

export const menuListW = [
  {
    index: 0,
    type: "면류",
    image: "/MenuImg/nuddle.png",
    dsc: "짜장면,짬뽕,차돌짬뽕,해물짜장면...",
  },
  {
    index: 1,
    type: "밥류",
    image: "/MenuImg/rice.png",
    dsc: "짜장밥,짬뽕밥,잡채밥,볶음밥...",
  },
  {
    index: 2,
    type: "세트메뉴",
    image: "/MenuImg/set_menu.jpg",
    dsc: "탕수육+짜장면+짜장면..",
  },
  {
    index: 3,
    type: "음료/주류",
    image: "/MenuImg/cider.jfif",
    dsc: "콜라,사이다,소주,맥주,이과두주..",
  },
  {
    index: 4,
    type: "스페셜1메뉴",
    image: "/MenuImg/vip_spcial1.jpg",
    dsc: "탕수육,사천탕수육,양장피..",
  },
  {
    index: 5,
    type: "스페셜2메뉴",
    image: "/MenuImg/vip_spcial2.jpg",
    dsc: "탕수육+팔보채+쟁반짜장..",
  },
  {
    index: 6,
    type: "사이드메뉴",
    image: "/MenuImg/side.jfif",
    dsc: "해물쟁반짜장2인,군만두,꽃빵..",
  },
  {
    index: 7,
    type: "시즌메뉴",
    image: "/MenuImg/season_menu.jpg",
    dsc: "굴짬뽕,홍굴짬뽕,콩국수,냉짬뽕..",
  },
];
